# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/colivier/src/hm2/external/hugin;/home/colivier/src/hm2/external/hugin/_sanity_build")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "/home/colivier/src/hm2/external/hugin/Debian/postinst")
set(CPACK_DEBIAN_PACKAGE_DEBUG "ON")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/home/colivier/miniforge3/envs/ubuntu/share/cmake-3.26/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "hugin built using CMake")
set(CPACK_GENERATOR "TBZ2")
set(CPACK_IGNORE_FILES "/_CPack_Packages/;/CMakeCache.txt$;\\.dir/;\\.tar\\.gz$;\\.tar\\.bz2$;\\.tar\\.Z$;\\.svn/;\\.cvsignore$;\\.swp$;~$;\\.#;/#;/src/api-doc/;/celeste/celeste_standalone$;/celeste/Config.h$;/celeste/training/celeste_train$;/tools/autooptimiser$;/tools/fulla$;/tools/nona$;/tools/vig_optimize$;/tools/align_image_stack$;/tools/tca_correct$;/tools/pto2mk$;/tools/hugin_hdrmerge$;/ptbatcher/PTBatcher$;/ptbatcher/PTBatcherGUI$;/hugin_base/test/open_file$;/matchpoint/matchpoint$;/hugin/hugin$;/whitepaper/;/lens_calibrate/test_lensFunc$;/lens_calibrate/calibrate_lens$;/nona_gui/nona_gui$;/stitch_project/hugin_stitch_project$;/deghosting/deghosting_mask$;/outdated/;/build/;/CVS/;/cmake_install.cmake$;/CMakeOutput.log$;/CPackConfig.cmake$;/CPackSourceConfig.cmake$;/Makefile$;/Makefile2$;/CMakeFiles/;/\\.libs/;/\\.deps/;\\.o$;\\.gmo$;\\.mo$;\\.a$;\\.lo$;\\.so$;\\.so\\.0$;\\.so\\.0\\.0$;\\.la$;Makefile\\.in$;/\\.hg/;/artwork-src/;\\.hgignore$;\\.hgtags$")
set(CPACK_INSTALLED_DIRECTORIES "/home/colivier/src/hm2/external/hugin;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/colivier/src/hm2/external/hugin/CMakeModules")
set(CPACK_NSIS_DISPLAY_NAME "hugin 2024.0.1.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "hugin 2024.0.1.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/colivier/src/hm2/external/hugin/_sanity_build/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "hugin-ptx@googlegroups.com")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/colivier/miniforge3/envs/ubuntu/share/cmake-3.26/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "hugin built using CMake")
set(CPACK_PACKAGE_FILE_NAME "hugin-2024.0.1")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "hugin 2024.0.1.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "hugin 2024.0.1.1")
set(CPACK_PACKAGE_NAME "hugin")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "2024.0.1.1")
set(CPACK_PACKAGE_VERSION_MAJOR "2024")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "1.1")
set(CPACK_PROJECT_CONFIG_FILE "/home/colivier/src/hm2/external/hugin/_sanity_build/CPackEnv.cmake")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/colivier/miniforge3/envs/ubuntu/share/cmake-3.26/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/home/colivier/miniforge3/envs/ubuntu/share/cmake-3.26/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/home/colivier/miniforge3/envs/ubuntu/share/cmake-3.26/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_RPM_SPEC_MORE_DEFINE "%define ignore #")
set(CPACK_RPM_USER_FILELIST "%ignore /usr/local;%ignore /usr/local/bin;%ignore /usr/local/lib;%ignore /usr/local/share;%ignore /usr/local/share/applications;%ignore /usr/local/share/man;%ignore /usr/local/share/man/man1")
set(CPACK_SET_DESTDIR "ON")
set(CPACK_SOURCE_GENERATOR "TBZ2")
set(CPACK_SOURCE_IGNORE_FILES "/_CPack_Packages/;/CMakeCache.txt$;\\.dir/;\\.tar\\.gz$;\\.tar\\.bz2$;\\.tar\\.Z$;\\.svn/;\\.cvsignore$;\\.swp$;~$;\\.#;/#;/src/api-doc/;/celeste/celeste_standalone$;/celeste/Config.h$;/celeste/training/celeste_train$;/tools/autooptimiser$;/tools/fulla$;/tools/nona$;/tools/vig_optimize$;/tools/align_image_stack$;/tools/tca_correct$;/tools/pto2mk$;/tools/hugin_hdrmerge$;/ptbatcher/PTBatcher$;/ptbatcher/PTBatcherGUI$;/hugin_base/test/open_file$;/matchpoint/matchpoint$;/hugin/hugin$;/whitepaper/;/lens_calibrate/test_lensFunc$;/lens_calibrate/calibrate_lens$;/nona_gui/nona_gui$;/stitch_project/hugin_stitch_project$;/deghosting/deghosting_mask$;/outdated/;/build/;/CVS/;/cmake_install.cmake$;/CMakeOutput.log$;/CPackConfig.cmake$;/CPackSourceConfig.cmake$;/Makefile$;/Makefile2$;/CMakeFiles/;/\\.libs/;/\\.deps/;\\.o$;\\.gmo$;\\.mo$;\\.a$;\\.lo$;\\.so$;\\.so\\.0$;\\.so\\.0\\.0$;\\.la$;Makefile\\.in$;/\\.hg/;/artwork-src/;\\.hgignore$;\\.hgtags$")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/colivier/src/hm2/external/hugin;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/colivier/src/hm2/external/hugin/_sanity_build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "hugin-2024.0.1")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/colivier/src/hm2/external/hugin/_sanity_build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
